#!/usr/bin/env bash
# vim: set ft=sh :
# shellcheck disable=SC2034

set -o pipefail -eu

source "../../duct"

# duct settings
DUCT_INIT_QUIET=true
DUCT_MSG_LEVEL=7
DUCT_DRY_RUN=false

RC="$1"
shift
CMD=( "$@" )

duct msg n "handling rc $RC for ${CMD[*]}"
